### ISSUE TITLE
Unquoting keys

### ISSUE THREAD

**Issue by tek** [limansky/mongoquery#2]
Is this supposed to work?

``` scala
    val a = "a"
    mq"{ $a: 1 }"
```

I get ``}' expected, but Variable found`

**Comment by limansky** [comment]
Well, in current version no, but I'm going to change this in SNAPSHOT soon to create predefined operators (so, it will be possible to write MongoDB operators without $ escaping).

**Comment by tek** [comment]
looking forward to it!

**Comment by pjgg** [comment]
I agree with Tek, something like this

val customQuery = "{name:{$$in: ['item1','item2']}}"
 mq"$customQuery"

Would be awesome!. In my case I am thinking to use this library that you developed for testing propose, so even if you give the chance to make conversions between StringJson to BSONDocument (ReactiveMongo) not as a Macro, would be fine!. 

Anyway you did a great Job!!!.

**Comment by limansky** [comment]
Hi @pjgg. There is one problem with mq"$query". In current implementation all interpolators are macros. So, all BSON is parsed on compile time, to some library dependent expression.
But this requires runtime parsing.

From the other side, I can add another interpolator, let's say mqr, which will use parsers I already have on runtime.

**Comment by pjgg** [comment]
Yes I think that this would be a good approach. A new interpolator "mqr",  a runtime interpolation!.

**Comment by limansky** [comment]
@pjgg I've created separate issue #3  for this feature.
