### ISSUE TITLE
Add Scala Mongo driver as installation option

### ISSUE THREAD

**Issue by kell18** [limansky/mongoquery#7]
Hi! Thank you for such an interesting library! :)
I'm trying to use it with https://github.com/mongodb/mongo-scala-driver which is now official driver for Mongo. Is it possible to adapt it for it?

Thank you!

**Comment by limansky** [comment]
Isn't this a duplicate of #4 ?

**Comment by kell18** [comment]
Yes, sorry, tangled in the libs titles :)
